openapi: 3.0.0
info:
  title: API PP4
  version: 1.0.0
  description: API RESTful para Práctica Profesionalizante IV
servers:
  - url: http://localhost:3114/api
paths:
  /areas:
    get:
      summary: Obtener todas las áreas
      responses:
        "200":
          description: Lista de áreas
    post:
      summary: Crear un área
      responses:
        "201":
          description: Área creada
  /areas/{id}:
    get:
      summary: Obtener un área por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Área encontrada
        "404":
          description: No encontrada
    put:
      summary: Actualizar un área
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Área actualizada
    delete:
      summary: Eliminar un área
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Área eliminada
